#MongoDB configuration
spring.data.mongodb.uri=${MONGODB_URI}

#Cloudinary configuration
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


#jwt information

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
